services:
  php:
    container_name: blumilk-version
    build:
      context: environment/php
    tty: true
    working_dir: /application
    user: ${CURRENT_UID:-1000}
    volumes:
      - .:/application
